language: java
jdk:
  - oraclejdk11
  - openjdk8
  - openjdk11

addons:
  sonarcloud:
    organization: "jsonurl"
    token:
      secure: "NyTKjEM4XBFb371O4di+XacUtJ4jAu3TMFaYhpnKfzZpi00wpBBsikK+Unvp+OqSCpbpvCbVD3SNJVEhfiKcGZHaGkFarOMgo0o9sAieSqFDzn3Tx4v6zVvC4FITJK10bX6YscoBIOU03xjR3ya31dBsrZJ2t8fxAbzvPDvUQxprA2ecvvvudb2X/C4YEF5tH4q3Fv9466lsTJqmoIcLTERVhI1/vfxwi/W0sWGI19u2wdtVac5yGchZTbpo2mhbhj8Rg48aJRovrVvY5LjPtRbBREsLO90WDNa5Kxab2vCaY0HPrUhCBgBXuB+3NSO+0zw0OezSQY1PSI/VmOmzvbrQvGg0D1QNWv9lIjKMNGQ2psPb8TTq8m5GGkHfKLLHuF6pOCKz3DqTFQUC/K2qRLkbYnQBGu0tPm36a2qg9LsxANvarkwNucM24H0F5Tx3X7hixQJVuuWBQgGetcHzeDZVfHQe4t8Gye/TojlCb1hAunblKgL+5TdTtwjvKzLr0ehXdnm77bNfB19YSRl2DopmTS3DkKOxiCs7dUiF+U0gUVx3WuGCOr0u0tkj8qgji5SeUTrFVeagLHOgWk2u9gZOGtAW2q8gy2Eew1rXN5DD1wKNdi+4sfAlNlULDRPkhjaaLnT++aUeyrVInonZ3p6AYs0UuRR8oMYadsjHc+0="

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  # mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=jsonurl_jsonurl-java
  - mvn -P jacoco clean compile test install sonar:sonar -Dsonar.projectKey=jsonurl_jsonurl-java

