language: java
jdk:
  - oraclejdk11
  - openjdk8
  - openjdk11

addons:
  sonarcloud:
    organization: "jsonurl"
    token:
      secure: "Fud/sAurIHJuAXTNBHbK/KgHFhGYieim45AQX99W6UAAV0l+ikiEW4oqRu0EwCjlyOcoO6ZYzGFEguK/IyvA5bzsU90vPdN0Xo5cJ91Xx7H6UW7IYV6RgFyQDXKHSB2KxLK3JKfY+8LiLypVxLydkq4q4RSy/pSHbBFt962Yc1tQ4mq6/z6ummy2TL4nuuPwMT6yDBGQeXAPG3C4SCZx3ter8FgtWE1RRYf4n25WpKHFGpUNPZalgw4BENNUXoGKMYqI7gLT497TYLh8w2Ncry5AebdJJqBvneq/98XlkDcp3G1xCnLpOWU2/85BPX2tkpDL0cpnUayd5arAGoeqS1oPzdd2WUnnbszjlp3GpcIFJV8btCVW3bRkNqBTikIGpR5MVQsQEtGBjEKHcGOHjWI4/SlT/5SM7LKhZGRy23riL8SgKXL9bCqNAVhgvsECXOHb14QOijdSf998vbH8q0xD+ugMpuu0fH7NG3WF8UJJPdpTf+8oxn3eVxoMyy1ptbhG7mmjj7fYJkwtYISh+3fcPwou5yJkOIUwiJ6rfb5KePDEAxpdR8UNg/EeaZ01cAliSFkQ3lN6KW0Y1QQ4QKfos6ktn6bF9wkBCPyCc8QGfSx5/EFHCxx0DLYsksA4YM8dnZOurWbWAs5RqtcHIVo8UMmTykrFtcq9/3hWZ/k="

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  # mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=jsonurl_jsonurl-java
  - mvn -P jacoco clean compile test install sonar:sonar -Dsonar.projectKey=jsonurl_jsonurl-java

