language: java
jdk:
  - oraclejdk11
  - openjdk8
  - openjdk11

addons:
  sonarcloud:
    organization: "jsonurl"
    token:
      secure: "jvbO7iJRe5FkxYQUU90VrrSfpXTe/fHIY4aIF50caBNk2ZW09mEatvTPwevj0Gbiq1upuPImgCJpbj4gnRpld6h5BU0bcsAM5uUX6f8BaKB7ToEWJjyxhQSC8qGf2j7b4bRryDVXns5XNNL1mIxZuGS53WeOVuMNx682Lu+QsGjiHvHzbt1RPMbtjHzoZu1ql7MdBEcYYy14qBfeicTDte+LxH3Qxyhn+YZepqfbpvK35S188WbqJXQ2VXdXayE+q/sZaUoHStvgbDIFQPW/fbVuIGSAix1fEAkuHooTmG92OMUJ5XNLJVNU+AP4jOmJfjEsDbkKtHjA5mGf3D5SdKGvclvXlyQ2gmhV43MyMA2bKhKO302AFPgEhk1YCec9K1HK5R75X6FmLS0ksq75jhhJ3Jvzh5Q2GnYFZF8DLebWOVYn/Y0UhuqGwvW57iQmmt/uID80IC2nTA5rhjxmYPS6bObc7XoYjMjww1ahiaLgPNrHhNP6FFP2H2kD3e8PwZioBRQmwF5ziBlWV+ugBrqiCg9C6ksPe6osqWXl73dYGem6sxBL6tn8s2LJgLvVVfEmMDIzwJ9m/Ih33r+k7eAwx5WX3a1F+ti/K4KPJLCo+lw6xJVpFfjUMdn3sfZCoviiQPlDR1t/VWRTAxEc6fVtv+KYS3ReZRvXtzLZpFE="

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  # mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=jsonurl_jsonurl-java
  - mvn -P jacoco clean compile test install sonar:sonar -Dsonar.projectKey=jsonurl_jsonurl-java

